import { useState } from 'react';
import { AdminDemoStore } from '../../../data/admin-demo-store';
import { demoDataset } from '../../../data/demo-dataset';
import '../admin.css';

export function UserManagementPage() {
  const [, refresh] = useState(0); const accounts = AdminDemoStore.listAccounts(); const projects = AdminDemoStore.listProjects();
  return <div className="admin-page"><p className="admin-eyebrow">ACCESS</p><h1>사용자 및 권한</h1><p className="admin-intro">역할은 고정되며 계정 상태와 기업·프로젝트 할당으로 데이터 범위를 정합니다.</p><section className="admin-table-panel"><table><thead><tr><th>사용자 / 이메일</th><th>역할</th><th>기업</th><th>프로젝트 배정</th><th>상태</th></tr></thead><tbody>{accounts.map((account) => <tr key={account.id}><td><strong>{account.name}</strong><br /><small>{account.email}</small></td><td>{label(account.role)}</td><td>{account.role === 'company' ? <select aria-label={`${account.name} 기업`} value={account.companyId ?? ''} onChange={(event) => { AdminDemoStore.updateAccount(account.id, { companyId: event.target.value }); refresh((n) => n + 1); }}><option value="">미지정</option>{demoDataset.companies.map((company) => <option key={company.id} value={company.id}>{company.label}</option>)}</select> : '—'}</td><td>{account.role === 'consultant' ? <div className="admin-checks">{projects.map((project) => <label key={project.id}><input type="checkbox" checked={account.assignedProjectIds.includes(project.id)} onChange={(event) => { const ids = event.target.checked ? [...account.assignedProjectIds, project.id] : account.assignedProjectIds.filter((id) => id !== project.id); AdminDemoStore.updateAccount(account.id, { assignedProjectIds: ids }); refresh((n) => n + 1); }} />{project.name}</label>)}</div> : account.assignedProjectIds.map((id) => projects.find((item) => item.id === id)?.name).filter(Boolean).join(', ') || '—'}</td><td><button type="button" onClick={() => { AdminDemoStore.updateAccount(account.id, { status: account.status === 'active' ? 'inactive' : 'active' }); refresh((n) => n + 1); }}>{account.status === 'active' ? '활성 · 중지' : '중지 · 활성화'}</button></td></tr>)}</tbody></table></section></div>;
}
function label(role: string) { return role === 'company' ? '기업 고객' : role === 'consultant' ? '컨설턴트' : '시스템 관리자'; }
